#!/usr/bin/bash
# This should be in /etc/rc.local

# su - pi -c "screen -dm -S /home/pi/TrafikantenLED/cppled/a.out" # Deprecated
sudo su - pi -c "screen -dm -S cppled /home/pi/TrafikantenLED/cppled/a.out"
